server:
   port: 8082

spring:
   application:
      name: fuel-app-api-gateway
   cloud:
      gateway:
         discovery:
            locator:
              enabled: true
         routes:
            - id: fuel-app-parser-service
              uri: https://e-petrol-price-parser.herokuapp.com/
#              predicates:
#                 - Path=/api/v1/fuel-info, /api/v1/fuel-info/update
#                 - Method=GET, POST
#            - id: fuel-app-car-parser-service
#              uri: lb://fuel-app-car-parser-service
#              predicates:
#                 - Path=/parse
#                 - Method=POST

eureka:
   client:
      service-url:
         defaultZone: https://e-petrol-eureka.herokuapp.com/eureka
