server:
   port: 8082

spring:
   application:
      name: fuel-app-api-gateway
   cloud:
      gateway:
         discovery:
            locator:
              enabled: true
         routes:
            - id: fuel-app-parser-service
              uri: https://e-petrol-price.herokuapp.com/
              predicates:
                 - Path=/api/v1/fuel-info, /api/v1/fuel-info/update, /api/v1/fuel-info/logo, /api/v1/fuel-info/details
                 - Method=GET, POST, PUT
            - id: fuel-app-car-parser-service
              uri: https://e-petrol-car.herokuapp.com/
              predicates:
                 - Path=/api/v1/car-data/parse-all, /api/v1/car-data/parse-car-brand-pages, /api/v1/car-data/parse-car-pages
                 - Method=POST

eureka:
   client:
      service-url:
         defaultZone: https://e-petrol-eureka.herokuapp.com/eureka
